name: C/C++ CI

on: 
  push:
    branches:
      - master
      - develop
      - develop_yml

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libmysqlclient-dev
    - name: build step 1
      run: cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=../release .
    - name: build step 2
      run: make && make install
